name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  pull_request:
    branches:
      - master
jobs:
  lint_on_PRs:
    runs-on: ubuntu-latest
    steps:
      - run: npm ci && npm run lint
